### ISSUE TITLE
P3 EXPORT AS IMAGE: In Square mode, export as image includes white space

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-vis-heatmap#35]
In Chrome, Demo performing testing.

Expected Behavior: Set "Square mode" Export as image, creates an image of just the chart

Actual Behavior: Set "Square mode" Export as image, creates an image of chart with a lot of white space to the right of it.
![screen shot 2018-03-05 at 4 10 24 pm](https://user-images.githubusercontent.com/21231643/37006958-c2484048-208f-11e8-938e-e95a6f67f988.png)

**Comment by drewharvey** [comment]
This happens because the chart width defined is this size. `squareMode` will adjust the size of the cells, but will not change the actual dimensions of the chart area (defined by `width` and `height` properties). 

The squareMode was not a specified feature, but was requested by the charts team.  There is no spec and so the functionality is basic.  I think enhancements to the feature should be created as separate issues.

**Comment by drewharvey** [comment]
Agreed to auto resize width and height to remove dead whitespace.
